version: '3'
services:
  php:
    container_name: swoole_php_host
    build: ./php7.2
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
      - ./php7.2/crontab:/etc/crontab
    networks:
      - swoole_net
    command:
      - docker-entrypoint
  nginx:
    container_name: swoole_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 80:80
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - swoole_net
  redis:
    container_name: swoole_redis_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/redis5:v1
    ports:
      - 6379:6379
    volumes:
      - ./redis5/conf:/usr/local/etc/redis
      - ./redis5/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - swoole_net
networks:
  swoole_net:
    driver: bridge