version: '3'
services:
  php:
    container_name: my_php_host
    build: ./php7.2
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - ./web:/opt/web
      - /etc/localtime:/etc/localtime
      - ./php7.2/crontab:/etc/crontab
      - /opt/walle_data:/opt/walle_data
    networks:
      - my_net
    command:
      - docker-entrypoint
  nginx:
    container_name: my_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - ./web:/opt/web
      - /etc/localtime:/etc/localtime
      - /opt/walle_data:/opt/walle_data
    networks:
      - my_net
  redis:
    container_name: my_redis_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/redis5:v1
    ports:
      - 6379:6379
    volumes:
      - ./redis5/conf:/usr/local/etc/redis
      - ./redis5/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - my_net
  mysql:
    container_name: my_mysql_host
    build: ./mysql5.7
    environment: 
        MYSQL_ROOT_PASSWORD: jian12345chi
    ports:
      - 3306:3306
    networks:
      - my_net
networks:
  my_net:
    driver: bridge