version: '3'
services:
  php:
    container_name: cbs_php_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/php_7.2:v1
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/gitsource:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - cbs_net
  nginx:
    container_name: cbs_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 10080:10080
      - 80:80
      - 443:443
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - /media/psf/gitsource:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - cbs_net
networks:
  cbs_net:
    driver: bridge