version: '3'
services:
  php:
    container_name: syh_php_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/php_7.2:v1
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - ./web:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - syh_net
  php2:
    container_name: syh_php_host2
    image: registry.cn-beijing.aliyuncs.com/excellent3207/php_7.2:v1
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - ./web:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - syh_net
  nginx:
    container_name: syh_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 18088:18088
      - 18089:18089
      - 80:80
      - 443:443
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - ./web:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - syh_net
  redis:
    container_name: syh_redis_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/redis5:v1
    ports:
      - 6379:6379
    volumes:
      - ./redis5/conf:/usr/local/etc/redis
      - ./redis5/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - syh_net
networks:
  syh_net:
    driver: bridge