version: '3'
services:
  php:
    container_name: my_php_host
    build: ./php7.2
    ports:
      - 9501:9501
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
      - ./php7.2/crontab:/etc/crontab
    networks:
      - my_net
    command:
      - docker-entrypoint
  nginx:
    container_name: my_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 80:80
      - 8080:8080
      - 10080:10080
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - my_net
  redis:
    container_name: my_redis_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/redis5:v1
    ports:
      - 6379:6379
    volumes:
      - ./redis5/conf:/usr/local/etc/redis
      - ./redis5/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - my_net
  mysql:
    container_name: my_mysql_host
    build: ./mysql5.7
    environment: 
        MYSQL_ROOT_PASSWORD: jian12345chi
    ports:
      - 3306:3306
    volumes:
      - ./mysql5.7/data:/var/lib/mysql
      - ./mysql5.7/conf:/etc/mysql
    networks:
      - my_net
  elasticsearch:
    container_name: my_elasticsearch_host
    build: ./elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
    networks:
      - my_net
networks:
  my_net:
    driver: bridge