version: '3'
services:
  php:
    container_name: syh_his_php_host
    build: ./php7.2
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
      - ./php7.2/crontab:/etc/crontab
    networks:
      - syh_his_net
  nginx:
    container_name: syh_his_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 10081:10081
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - syh_his_net
networks:
  syh_his_net:
    driver: bridge