version: '3'
services:
  php:
    hostname: php_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/php_7.2:v1
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/gitsource:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
  nginx:
    hostname: nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v1
    ports:
      - 18088:80
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - /media/psf/gitsource:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
    links:
      - "php:php_host"
  php2:
    hostname: php_host2
    image: registry.cn-beijing.aliyuncs.com/excellent3207/php_7.2:v1
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/gitsource:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
  nginx2:
    hostname: nginx_host2
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v1
    ports:
      - 18089:80
    volumes:
      - ./nginx1.15.5/conf2:/etc/nginx
      - /media/psf/gitsource:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
    links:
      - "php:php_host2"
  redis:
    hostname: redis_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/redis5:v1
    ports:
      - 6379:6379
    volumes:
      - ./redis5/conf:/usr/local/etc/redis
      - ./redis5/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
networks:
  nginx_php_net:
    driver: bridge