version: '3'
services:
  php:
    container_name: syh_php_host
    build: ./php7.2
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
    command:
      - docker-entrypoint
  php2:
    container_name: syh_php_host2
    build: ./php7.2
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
    command:
      - docker-entrypoint
  nginx:
    container_name: syh_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 18088:18088
      - 18089:18089
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - /media/psf/git:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
  redis:
    container_name: syh_redis_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/redis5:v1
    ports:
      - 6379:6379
    volumes:
      - ./redis5/conf:/usr/local/etc/redis
      - ./redis5/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - nginx_php_net
networks:
  nginx_php_net:
    driver: bridge