version: '3'
services:
  php:
    container_name: syh_his_php_host
    build: ./php7.2
    volumes:
      - ./php7.2/conf:/usr/local/etc
      - ./web:/opt/web
      - /etc/localtime:/etc/localtime
      - ./php7.2/crontab:/etc/crontab
      - ./php7.2/docker-entrypoint.sh:/docker-entrypoint.sh
    networks:
      - syh_his_net
  nginx:
    container_name: syh_his_nginx_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/nginx_1.15.5:v2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx1.15.5/conf1:/etc/nginx
      - ./web:/opt/web
      - /etc/localtime:/etc/localtime
    networks:
      - syh_his_net
  redis:
    container_name: syh_his_redis_host
    image: registry.cn-beijing.aliyuncs.com/excellent3207/redis5:v1
    ports:
      - 6379:6379
    volumes:
      - ./redis5/conf:/usr/local/etc/redis
      - ./redis5/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - syh_his_net
networks:
  syh_his_net:
    driver: bridge